// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzz2tc7J1JvP5MV5m5buaCFS6axIgRBkU',
    appId: '1:458936831536:web:828c7e5929e4b9d618e7f5',
    messagingSenderId: '458936831536',
    projectId: 'fixer-4f39a',
    authDomain: 'fixer-4f39a.firebaseapp.com',
    storageBucket: 'fixer-4f39a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSF9DRD4wIhmegkjfMpRRQPDa1YrtIR3Y',
    appId: '1:458936831536:android:c94fc9e11a686a1a18e7f5',
    messagingSenderId: '458936831536',
    projectId: 'fixer-4f39a',
    storageBucket: 'fixer-4f39a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS458PyIQr8PueM96CAX6lrdh97KTeGrA',
    appId: '1:458936831536:ios:14e50455b0343bcf18e7f5',
    messagingSenderId: '458936831536',
    projectId: 'fixer-4f39a',
    storageBucket: 'fixer-4f39a.appspot.com',
    iosClientId: '458936831536-3usf2mjkhdjqlhs8gjinn1sht48597su.apps.googleusercontent.com',
    iosBundleId: 'com.fixer.fixer',
  );
}
